package NewLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum JavaVersion {
  _1_8("1.8", "1.8"),
  _1_7("1.7", "1.7");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<JavaVersion> getConstants() {
    List<JavaVersion> list = ListSequence.fromList(new LinkedList<JavaVersion>());
    ListSequence.fromList(list).addElement(JavaVersion._1_8);
    ListSequence.fromList(list).addElement(JavaVersion._1_7);
    return list;
  }
  public static JavaVersion getDefault() {
    return JavaVersion._1_8;
  }
  public static JavaVersion parseValue(String value) {
    if (value == null) {
      return JavaVersion.getDefault();
    }
    if (value.equals(JavaVersion._1_8.getValueAsString())) {
      return JavaVersion._1_8;
    }
    if (value.equals(JavaVersion._1_7.getValueAsString())) {
      return JavaVersion._1_7;
    }
    return JavaVersion.getDefault();
  }
  private String myValue;
  JavaVersion(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
