package NewLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum SpringPackaging {
  jar("jar", "jar"),
  war("war", "war");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<SpringPackaging> getConstants() {
    List<SpringPackaging> list = ListSequence.fromList(new LinkedList<SpringPackaging>());
    ListSequence.fromList(list).addElement(SpringPackaging.jar);
    ListSequence.fromList(list).addElement(SpringPackaging.war);
    return list;
  }
  public static SpringPackaging getDefault() {
    return SpringPackaging.jar;
  }
  public static SpringPackaging parseValue(String value) {
    if (value == null) {
      return SpringPackaging.getDefault();
    }
    if (value.equals(SpringPackaging.jar.getValueAsString())) {
      return SpringPackaging.jar;
    }
    if (value.equals(SpringPackaging.war.getValueAsString())) {
      return SpringPackaging.war;
    }
    return SpringPackaging.getDefault();
  }
  private String myValue;
  SpringPackaging(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
