package NewLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptSpringSettings = new ConceptDescriptorBuilder("NewLanguage.structure.SpringSettings", MetaIdFactory.conceptId(0xf4aa25f0e5104232L, 0xb00df5a6a39c2ec9L, 0x23a30f0fec21b9bcL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2567912773591920168L, "host"), new ConceptDescriptorBuilder.Prop(2567912773591920176L, "description"), new ConceptDescriptorBuilder.Prop(2567912773591920187L, "packaging"), new ConceptDescriptorBuilder.Prop(2567912773591920206L, "baseName"), new ConceptDescriptorBuilder.Prop(2567912773591920223L, "javaVersion"), new ConceptDescriptorBuilder.Prop(2567912773591920243L, "version")).properties("host", "description", "packaging", "baseName", "javaVersion", "version").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptSpringSettings);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0f, conceptFqName)) {
      case 0:
        return myConceptSpringSettings;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0f = new String[]{"NewLanguage.structure.SpringSettings"};
}
